### ISSUE TITLE
FE login doesn't work since TYPO3 9.5.23

### ISSUE THREAD

**Issue by tobiasschaeferptb** [visol/ext-cabag_loginas#9]
Hello,

since the TYPO3 update 9.5.23 the FE login with cabag_loginas doesn't work anymore.
This is related to the changed way of storing the session IDs.
Take a look at:
https://get.typo3.org/release-notes/9.5.23
2020-11-17 dc26a4ac1a [SECURITY] Protect persisted session IDs from being used directly (thanks to Oliver Hader)
https://github.com/TYPO3/TYPO3.CMS/commit/dc26a4ac1a

It would be very nice if the extension could be adapted for this.

Best regards,
Tobias Schäfer

**Comment by lorenzulrich** [comment]
As discussed by e-mail, this repo is a former and outdated friendly fork of EXT:cabag_loginas. The up-to-date repo can be found at https://gitlab.cabag.ch/cabag/ext-cabag_loginas. I also added a note to this repo.
